# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(809, 474)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(70, 80, 541, 257))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        self.look_ahead = QtWidgets.QPushButton(Dialog)
        self.look_ahead.setGeometry(QtCore.QRect(620, 190, 141, 31))
        self.look_ahead.setObjectName("look_ahead")
        self.create_schedule = QtWidgets.QPushButton(Dialog)
        self.create_schedule.setGeometry(QtCore.QRect(620, 160, 141, 31))
        self.create_schedule.setObjectName("create_schedule")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 50, 81, 16))
        self.label.setObjectName("label")
        self.recommendations = QtWidgets.QPushButton(Dialog)
        self.recommendations.setGeometry(QtCore.QRect(620, 130, 141, 31))
        self.recommendations.setObjectName("recommendations")
        self.preferences = QtWidgets.QPushButton(Dialog)
        self.preferences.setGeometry(QtCore.QRect(620, 100, 141, 31))
        self.preferences.setObjectName("preferences")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "8 am"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "12 pm"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Monday"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Tuesday"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Wednesday"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Thursday"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Friday"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "course1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "course2"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "course1"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "course3"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "course3"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.look_ahead.setText(_translate("Dialog", "Look Ahead"))
        self.create_schedule.setText(_translate("Dialog", "Create Schedule"))
        self.label.setText(_translate("Dialog", "ScheduleMe"))
        self.recommendations.setText(_translate("Dialog", "Recommendations"))
        self.preferences.setText(_translate("Dialog", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

